### ISSUE TITLE
Unbound type variables in constraints

### ISSUE THREAD

**Issue by CraigFe** [ocaml-sf/learn-ocaml-corpus#31]
I've been working through the excellent new OCaml exercises and noticed a lot of instances of unbound type variables in constraints as in this example taken from the "Enumerating Trees" exercise:

```ocaml
let product (enum1 : 'a enum) (enum2 : 'b enum) : ('a * 'b) enum =
  (* TO DO: Complete this definition. *)
  raise TODO
```

These are something of a [personal dislike](https://www.craigfe.io/posts/polymorphic-type-constraints) of mine, as I find they lead students into false reasoning about constraints + polymorphism. This could be re-written to use an explicitly-polymorphic constraint, with or without locally-abstract types:

```ocaml
let product : 'a 'b. 'a enum -> 'b enum -> ('a * 'b) enum =
  fun enum1 enum2 ->
    (* TO DO: Complete this definition. *)
    raise TODO

let product : type a b. a enum -> b enum -> (a * b) enum =
  fun enum1 enum2 ->
    (* TO DO: Complete this definition. *)
    raise TODO
```

which sadly loses the direct coupling of parameters to types but does at least enforce a polymorphic definition.

Perhaps changes of this sort could be applied throughout the course? I'm happy to make a PR myself, but would appreciate a general nod of approval first.

**Comment by gasche** [comment]
(cc @fpottier, the author of the exercises)

My impression is that for now "implicit bound somewhat-polymorphic variables" is the norm/idiom in OCaml, and preference for explicit binding (which makes sense to me) is not strong enough of an argument to deviate from the norm. In addition, the exercises are meant for not-so-expert users, so I am not sure about using more advanced language features (the main point being that they are less common and more surprising.)

Personally I think the language needs to make explicit type-variable binding more convenient before we use it more widely.

**Comment by fpottier** [comment]
Hi Craig! Indeed, I too have been complaining for some time about the fact that type variables are not explicitly bound, so two crucial pieces of information are lacking, namely *where* the variable is bound and *how* it is bound (universally or existentially).

For the time being, though, the most common style in OCaml is the one I have been using in the exercises (without explicit binders). As you point out, introducing explicit universal quantifiers lets the typecheker catch more mistakes, but it's also more verbose. Furthermore, there are unfortunately several syntaxes for explicit universal quantifiers, each of which has its own advantages and disadvantages. The syntaxes you give decouple the formal parameters from their types. There is another one, which doesn't have this drawback:

```
let product (type a b) (enum1 : a enum) (enum2 : b enum) : (a * b) enum = ...
```

Unfortunately, this syntax has the drawback that one must explain why type variables are sometimes written `'a` and sometimes written `a`, something which (IMHO) has no good explanation except for historical reasons.

I should note that some of the exercises involve GADTs and polymorphic recursion; in those exercises, explicit bindings must be used (and I must say that I can never remember which of the several possible syntaxes is the one that really works; all others are rejected by the typechecker with obscure messages).

In the end, it's difficult to choose between different kinds of evil.

**Comment by CraigFe** [comment]
Thanks both for the well thought-out replies. Perhaps I should have been a bit less terse in my initial post; allow me to clarify my perspective for the record.

I'm aware of the drawbacks of explicit polymorphic annotations w.r.t. verbosity and syntactically decoupling the formal parameters from their types but – in my limited experience with teaching OCaml – have found them to be a good trade-off w.r.t. getting better error messages and creating fewer misconceptions early on. For this reason, I wouldn't recommend the pseudo type parameter syntax `(type a)` here – even for non-recursive definitions – since I've found it produces error messages that confuse students.

In short: an advanced syntax can be searched for and taught about whereas a misunderstood one leaves the user staring at the code wondering where they went wrong with little recourse. I actually think this style goes as far as to be explicitly misleading, setting up alpha-equivalences between the `'a`s and the `'b`s that is not reflected in OCaml's interpretation.

```ocaml
let product (enum1 : 'a enum) (enum2 : 'b enum) : ('a * 'b) enum =
```

In my view, the fact that the exercises are intended for beginners is precisely _why_ the more verbose / precise form would fit here: it's more advanced but surely less surprising in its behaviour, leaving a safety net for those who don't yet know the ins and outs of the type system. As an aside, I personally have not found the use of imprecise constraints on polymorphic functions to be the norm / convention in OCaml code in the wild, but perhaps I am lucky.

Regardless, I respect your different conclusions and will leave you in peace :slightly_smiling_face: Thanks for your time and for these excellent courses.

**Comment by fpottier** [comment]
> In my view, the fact that the exercises are intended for beginners is precisely _why_ the more verbose / precise form would fit here

I tend to agree with you. As a related example, when teaching (and in my code as a result) I have abandoned the use of the keyword `function`, preferring to write `fun foo -> match foo with`, even though it is more verbose, because it is usually easier to read and understand.

I would not be opposed to using the explicit form `let product : 'a 'b. 'a enum -> 'b enum -> ('a * 'b) enum = ...`.

**Comment by gasche** [comment]
This discussion reminded me that we have things we could change on the compiler side to improve the picture here. I'm thinking in particular of the proposal to allow users to use `'_a` as flexible inference variables, and gradually transition to using `'a` only for rigid variables. I may look into implementing some of that.

**Comment by fpottier** [comment]
One could indeed argue that flexible variables are an advanced feature that is rarely needed in practice, and that beginners need not be exposed to them.
